apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: faj5wua2n-python 
  janus-idp.io/tekton: faj5wua2n-python
  backstage.io/kubernetes-id: faj5wua2n-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: faj5wua2n-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  