apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: faj5wua2n-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: faj5wua2n-python 
  name: faj5wua2n-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: faj5wua2n-python 
